### ISSUE TITLE
instructions fail

### ISSUE THREAD

**Issue by cstachon** [rkaczorek/indi-mqtt#1]
1. the tar create different directory - so did a mv to pyindi-client

2. sudo python etc fails 

cd pyindi-client
astroberry@astroberry:~/pyindi-client $ sudo python3 setup.py install
Unable to find libindiclient.a in ['/usr/lib/arm-linux-gnueabihf', '/usr/lib', '/usr/lib64', '/lib', '/lib64', '/usr/local/lib']
Please specify a path where to find libindiclient.a in the setup.py script
Exiting

dont think i missed anything

**Comment by cstachon** [comment]
ok so i follwed the extra's in Jochym github 

apt-get install python-setuptools
apt-get install python-dev
apt-get install libindi-dev
apt-get install swig

it got further but still failed :-

sudo python3 setup.py install
running install
running build_ext
building '_PyIndi' extension
swigging indiclientpython.i to indiclientpython_wrap.cpp
swig -python -v -Wall -c++ -threads -I/usr/include -I/usr/include/libindi -I/usr/local/include/libindi -o indiclientpython_wrap.cpp indiclientpython.i
Language subdirectory: python
Search paths:
   ./
   /usr/include/
   /usr/include/libindi/
   /usr/local/include/libindi/
   ./swig_lib/python/
   /usr/share/swig3.0/python/
   ./swig_lib/
   /usr/share/swig3.0/
Preprocessing...
Starting language-specific parse...
/usr/include/libindi/baseclient.h:39: Warning 322: Redundant redeclaration of 'MAXRBUF',
/usr/include/libindi/indibase.h:8: Warning 322: previous declaration of 'MAXRBUF'.
/usr/include/libindi/baseclient.h:270: Warning 325: Nested struct not currently supported (BLOBMode ignored)
/usr/include/libindi/basedevice.h:29: Warning 322: Redundant redeclaration of 'MAXRBUF',
/usr/include/libindi/indibase.h:8: Warning 322: previous declaration of 'MAXRBUF'.
Processing types...
C++ analysis...
/usr/include/libindi/baseclient.h:61: Warning 403: Class 'INDI::BaseClient' might be abstract, no constructors generated,
/usr/include/libindi/indibase.h:84: Warning 403: Method INDI::BaseMediator::newDevice(INDI::BaseDevice *) might not be implemented.
Processing nested classes...
Generating wrappers...
creating build
creating build/temp.linux-armv7l-3.7
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/libindi -I/usr/local/include/libindi -I/usr/include/python3.7m -c indiclientpython_wrap.cpp -o build/temp.linux-armv7l-3.7/indiclientpython_wrap.o -std=c++11
creating build/lib.linux-armv7l-3.7
arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.7/indiclientpython_wrap.o /usr/lib/arm-linux-gnueabihf/libindiclient.a -lz -lcfitsio -lnova -o build/lib.linux-armv7l-3.7/_PyIndi.cpython-37m-arm-linux-gnueabihf.so
/usr/bin/ld: cannot find -lcfitsio
/usr/bin/ld: cannot find -lnova
collect2: error: ld returned 1 exit status
error: command 'arm-linux-gnueabihf-g++' failed with exit status 1

**Comment by rkaczorek** [comment]
You are missing:
- libcfitsio-dev
- libnova-dev

**Comment by cstachon** [comment]
ok that worked

**Comment by rkaczorek** [comment]
Fixed pyindi-client-0.2.4 has been just released!
Now indi-mqtt works without manual install of pyindi-client.
