### ISSUE TITLE
Question :- Changes to Indi properties

### ISSUE THREAD

**Issue by cstachon** [rkaczorek/indi-mqtt#4]
Are you supposed to be able to change (set) properties  - e.g. ISO via MQTT ?
Tried it and it changed for 1 sec then reverts back to original setting nothing changes in CCD!

**Comment by cstachon** [comment]
Guess looking at the source its read only - at the moment !

**Comment by rkaczorek** [comment]
It is a publisher only. No changes are possible to INDI properties at the moment.
