### ISSUE TITLE
Feature request - Poll on demand

### ISSUE THREAD

**Issue by cstachon** [rkaczorek/indi-mqtt#5]
I know it would mean adding a subscribe to your python code but could we have a method to demand a poll at "root" and "devices" level. This would allow the polling to be set off(poll=0) or very long intervals.

e.g. Observatory/poll/ 0 or 1 (yes or no) mean produce data as at present - all

Observatory/telescope/poll just telescope data 

When your publisher gets a request to poll it then resets the poll flag.

**Comment by rkaczorek** [comment]
This is standard functionality of MQTT protocol. To subscibe to a topic you can use:
- full topic name e.g. observatory/telescope/connection/connect -> one value is returned
- single level wildcard e.g. observatory/+/connection/connect -> values are returned for each device
- multilevel wildcard e.g. observatory/telescope/# -> values are returned only for telescope

You can find details here: https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

**Comment by cstachon** [comment]
Think we are at cross purposes here 

 I do NOT want Indi-mqtt to loop with an loop interval time of X secs  - i.e. Indi-mqtt pushes the data to MQTT every X seconds.

  Instead  Indi-mqtt should only send data to MQTT when it receives a message via topic called "ROOT"/poll - e.g. observatory/poll   The only exception would be on boot up when Indi-mqtt sends the data once and then waits for the poll message

I know about Std MQTT filtering,wildcards etc but this isn't about that !

Dont worry about it ! :-)

**Comment by rkaczorek** [comment]
I misinterpreted your need. This can be achieved by either two-directional communication as you suggest or publishing only parameters which change. Both approaches are valid and I will consider them in further development

**Comment by rkaczorek** [comment]
Polling feature has been implemented. Please test and report back
