### ISSUE TITLE
FR: Support of two or more devices per category

### ISSUE THREAD

**Issue by skolarianer** [rkaczorek/indi-mqtt#6]
It seems that only the values of one device per category are published. If I use e.g. Pegasus PPB – which is recognized as a weather device – and OpenWeatherMap simultaneously only the data of the PPB is published.
It'd be great if the values of all connected devices were published.

**Comment by rkaczorek** [comment]
Can you see both devices when running indi_getprop in a terminal?

**Comment by skolarianer** [comment]
Yes, `indi_getprop` lists everything from both devices.
(And this time only the values from OpenWeatherMap are reported in MQTT Explorer while the values from the PPB are missing.)

**Comment by rkaczorek** [comment]
Fixed. Please test and report back

**Comment by skolarianer** [comment]
Yes, it works for me now. Thanks!

(Sorry for the late response …  I somehow missed the notifcation.)
