### ISSUE TITLE
ability to provide mqtt username/password

### ISSUE THREAD

**Issue by jrsphoto** [rkaczorek/indi-mqtt#7]
I'm using indi-mqtt in in conjunction with my home automation system, Home Assistant.  Within Home Assistant I have Eclipse-MQTT running and configured for specific usernames and passwords.  I don't see a way to specify them either on the command line or from within the config file.  Is this something you can add?

**Comment by rkaczorek** [comment]
Thanks for the request. I will add authentication mechanism. Stay tuned

**Comment by rkaczorek** [comment]
Please test the latest release and provide feedback.

**Comment by jrsphoto** [comment]
I'll test this tonight.. thank you!
