### ISSUE TITLE
Have indi-mqtt.py report client name to mqtt broker 

### ISSUE THREAD

**Issue by jrsphoto** [rkaczorek/indi-mqtt#8]
Another feature request for you.  Hope I'm not too annoying.  

When I connect to the MQTT Broker (Eclipse MQTT) from MQTT Explorer,  it passes its client name to the broker so when I look in the logs, I can tell what client was connecting:

```
1590812963: New client connected from 192.168.1.86 as mqtt-explorer-7ec6fbe1 (p2, c1, k60).
1590812979: New connection from 192.168.1.86 on port 1883.
1590812979: New client connected from 192.168.1.86 as auto-8095885E-916F-4FC8-28BB-C6C43779BB78 (p2, c1, k60).
1590812979: Client auto-8095885E-916F-4FC8-28BB-C6C43779BB78 disconnected.
```
The connection "192.168.1.86 as auto-8095..." is from indi-mqtt.py, would it be possible for it to identify itself in the same way that mqtt-explorer does in the first log entry?

**Comment by jrsphoto** [comment]
by the way, amazing images you have on Astrobin!

**Comment by rkaczorek** [comment]
Thanks John. I'm glad you like the images.
Sure, I will take a look at client name. Your input is most welcome! This is how users drive development in open source world.

**Comment by rkaczorek** [comment]
Please test the latest release and provide feedback.

**Comment by jrsphoto** [comment]
Sorry for the delay.. I'll check this out tonight and let you know.
